openapi: 3.0.0
info:
  description: "A simple Demo Api Document"
  version: "1.0.0"
  title: "Demo Api"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
- url: localhost:8080
  description: Development server
tags:
- name: "player"
  description: "Operations about Player"
- name: "team"
  description: "Operations about Team"

paths:
  /players:
    get:
      tags:
      - "player"
      summary: "Get all players"
      operationId: "getAllPlayers"
      responses:
        "200":
          description: "successful operation"
          content: 
            application/json :
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Player"
            application/xml:
              schema:
                $ref: '#/components/schemas/Player'
        "404":
          description: "Nothing found"
    
#post may add here under same path    


  /teams:
    get:
      tags:
      - "team"
      summary: "Get all teams"
      operationId: "getAllTeams"
      responses:
        "200":
          description: "successful operation"
          content:
            appication/json: 
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Team"
            application/xml:
              schema:
                $ref: '#/components/schemas/Team'
        "404":
          description: "Nothing found"
 #post may add here under same path     
    

    
components:
  schemas: 
    Player:
      type: "object"
      required: 
      - "playerId"
      - "playerName"
      properties:
        playerId:
          type: "integer"
          format: "int64"
        playerName:
          type: "string"
        team:
          $ref: "#/components/schemas/Team"
      xml: 
        name: "Player"
    Team:
      type: "object"
      required: 
      - "teamId"
      - "teamName"
      properties:
        teamId:
          type: "integer"
          format: "int64"
        teamName: 
          type: "string"
      xml: 
        name: "Team"
    User: 
      type: "object"
      required: 
      - "userName"
      - "password"
      properties: 
        id: 
          type: "integer"
          format: "int64"
        userName: 
          type: "string"
        password:
          type: "string"
        active: 
          type: "boolean"
        roles:
          type: "string"
